# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 05:16
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityDict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='城市')),
                ('desc', models.TextField(verbose_name='城市描述')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='景区名称')),
                ('category', models.CharField(choices=[('1', '热卖'), ('2', '人气'), ('3', '畅游')], default='1', max_length=20, verbose_name='景区类别')),
                ('desc', models.TextField(verbose_name='景区描述')),
                ('detail', DjangoUeditor.models.UEditorField(verbose_name='景区详情')),
                ('tag', models.CharField(default='全国知名', max_length=10, verbose_name='景区标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏数')),
                ('visit_nums', models.IntegerField(default=0, verbose_name='参观人数')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否是轮播图')),
                ('image', models.ImageField(default='', upload_to='spot/%Y/%m', verbose_name='封面图')),
                ('address', models.CharField(max_length=150, verbose_name='景区地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '景区信息',
                'verbose_name_plural': '景区信息',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='门票名字')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('category', models.CharField(choices=[('1', '联票'), ('2', '普通票'), ('3', '学生票')], default='1', max_length=20, verbose_name='门票类别')),
                ('desc', models.TextField(verbose_name='门票描述')),
                ('detail', DjangoUeditor.models.UEditorField(verbose_name='门票详情')),
                ('tag', models.CharField(choices=[('1', '全国知名'), ('2', '热门门票'), ('3', '5A级景区')], default='1', max_length=20, verbose_name='门票标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('image', models.ImageField(default='', upload_to='ticket/%Y/%m', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.Spot', verbose_name='所属景区')),
            ],
            options={
                'verbose_name': '门票',
                'verbose_name_plural': '门票',
            },
        ),
        migrations.CreateModel(
            name='BannerSpot',
            fields=[
            ],
            options={
                'verbose_name': '轮播景区',
                'verbose_name_plural': '轮播景区',
                'proxy': True,
            },
            bases=('spots.spot',),
        ),
    ]
