# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 11:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerSpot',
            fields=[
            ],
            options={
                'verbose_name': '轮播景区',
                'proxy': True,
                'verbose_name_plural': '轮播景区',
            },
            bases=('spots.spot',),
        ),
        migrations.AlterModelOptions(
            name='spot',
            options={'verbose_name': '景区信息', 'verbose_name_plural': '景区信息'},
        ),
    ]
