# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 11:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_auto_20180326_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default=1, verbose_name='景区详情'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='detail',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='门票详情'),
            preserve_default=False,
        ),
    ]
