# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_auto_20180326_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='是否是轮播图'),
        ),
    ]
