# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0004_spot_is_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(default='', upload_to='spot/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default='', upload_to='ticket/%Y/%m', verbose_name='封面图'),
        ),
    ]
