# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 11:40
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='酒店详情'),
        ),
        migrations.AlterField(
            model_name='room',
            name='detail',
            field=DjangoUeditor.models.UEditorField(verbose_name='房间详情'),
        ),
    ]
