# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 11:45
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_auto_20180326_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='酒店详情'),
        ),
    ]
