# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_auto_20180326_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels.Hotel', verbose_name='所属酒店'),
        ),
    ]
