# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_auto_20180326_1201'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='students',
            new_name='buy_nums',
        ),
    ]
