# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_auto_20180326_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='hotel/%Y/%m', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(upload_to='hotelroom/%Y/%m', verbose_name='封面图'),
        ),
    ]
