# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-04 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='userinfo',
        ),
    ]
