# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 22:29
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zutuanyou', '0001_initial'),
        ('qinziyou', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0002_auto_20180414_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQinziyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='qinziyou.Qinziyou', verbose_name='亲子游')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户参加的亲子游',
                'verbose_name_plural': '用户参加的亲子游',
            },
        ),
        migrations.CreateModel(
            name='UserZutuanyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('schedule', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='zutuanyou.Zutuanyou', verbose_name='组团游')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户参加的组团游',
                'verbose_name_plural': '用户参加的组团游',
            },
        ),
        migrations.AlterField(
            model_name='userfavorite',
            name='fav_type',
            field=models.IntegerField(choices=[(1, '行程'), (2, '酒店房间'), (3, '景区门票'), (4, '组团游'), (5, '亲子游')], default=1, verbose_name='购买类型'),
        ),
    ]
