# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_hotelcomments_schedulecomments_spotcomments_userask_userfavorite_userhotel_userschedule_userspot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userschedule',
            old_name='course',
            new_name='schedule',
        ),
    ]
