# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180429_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userqinziyou',
            old_name='schedule',
            new_name='qinziyou',
        ),
        migrations.RenameField(
            model_name='userzutuanyou',
            old_name='schedule',
            new_name='zutuanyou',
        ),
    ]
