# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 16:52
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qinziyou',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='亲子游名字')),
                ('desc', models.CharField(max_length=300, verbose_name='亲子游描述')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, verbose_name='亲子游详情')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('image', models.ImageField(upload_to='schedule/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('tag', models.CharField(default='亲子游备注', max_length=10, verbose_name='亲子游备注')),
                ('youneed_konw', models.CharField(default='', max_length=300, verbose_name='行前须知')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='亲子游前往地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spots.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '亲子游',
                'verbose_name_plural': '亲子游',
            },
        ),
    ]
