# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-29 13:18
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='攻略名字')),
                ('desc', models.CharField(max_length=300, verbose_name='攻略描述')),
                ('detail', DjangoUeditor.models.UEditorField(blank=True, verbose_name='攻略详情')),
                ('category', models.CharField(choices=[('1', '经济型'), ('2', '畅玩型'), ('3', '高档型')], max_length=2, verbose_name='攻略级别')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('image', models.ImageField(blank=True, upload_to='hotel/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('tag', models.CharField(default='热门销售', max_length=10, verbose_name='攻略标签')),
                ('youneed_konw', models.CharField(default='', max_length=300, verbose_name='购买须知')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spots.CityDict', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '攻略',
                'verbose_name_plural': '攻略',
            },
        ),
    ]
