# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 05:16
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='行程名字')),
                ('desc', models.CharField(max_length=300, verbose_name='行程描述')),
                ('detail', DjangoUeditor.models.UEditorField(verbose_name='行程详情')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('image', models.ImageField(upload_to='schedule/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否是轮播图')),
                ('category', models.CharField(choices=[('1', '组团游'), ('2', '亲子游'), ('3', '自驾游')], max_length=2, verbose_name='旅游形式')),
                ('tag', models.CharField(default='行程备注', max_length=10, verbose_name='行程备注')),
                ('youneed_konw', models.CharField(default='', max_length=300, verbose_name='行前须知')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='景区地址')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spots.CityDict', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '行程',
                'verbose_name_plural': '行程',
            },
        ),
        migrations.CreateModel(
            name='BannerSchedule',
            fields=[
            ],
            options={
                'verbose_name': '轮播行程',
                'verbose_name_plural': '轮播行程',
                'proxy': True,
            },
            bases=('schedules.schedule',),
        ),
    ]
