# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 13:19
from __future__ import unicode_literals

import DjangoUeditor.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=52, verbose_name='行程名字')),
                ('desc', models.CharField(max_length=300, verbose_name='行程描述')),
                ('detail', DjangoUeditor.models.UEditorField(verbose_name='行程详情')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=2, verbose_name='难度')),
                ('learn_times', models.IntegerField(default=0, verbose_name='学习时长(分钟数)')),
                ('buy_nums', models.IntegerField(default=0, verbose_name='购买人数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('image', models.ImageField(upload_to='courses/%Y/%m', verbose_name='封面图')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击数')),
                ('is_banner', models.BooleanField(default=False, verbose_name='是否是轮播图')),
                ('category', models.CharField(default='后端', max_length=20, verbose_name='行程类别')),
                ('tag', models.CharField(default='', max_length=10, verbose_name='行程标签')),
                ('youneed_konw', models.CharField(default='', max_length=300, verbose_name='行前须知')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name_plural': '行程',
                'verbose_name': '行程',
            },
        ),
        migrations.CreateModel(
            name='BannerSchedule',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': '轮播行程',
                'verbose_name': '轮播行程',
            },
            bases=('schedules.schedule',),
        ),
    ]
