# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-26 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='image',
            field=models.ImageField(upload_to='schedule/%Y/%m', verbose_name='封面图'),
        ),
    ]
