# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 05:47
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='detail',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='行程详情'),
        ),
    ]
