# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-04-14 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_auto_20180414_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='price',
            field=models.IntegerField(default=0, verbose_name='价格'),
        ),
    ]
